spring.application.name=huSpark
server.port=8080
#server.servlet.context-path=/socio-api

# DataSource configuration
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Database connection properties
DB_HOST=localhost
DB_PORT=3306
DB_USER=root
DB_PASSWORD=pixiehollow19
DB_NAME=socio

# JPA / Hibernate configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.database=MYSQL
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# JWT properties
#jwt secret to support HSC256
app.jwtSecret=YourJwtSecretKey129132912931293919313919212099
#1 hour in ms token expiry time
app.jwtExpirationInMs=3600000 

# Multipart file properties
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB

# Spring Batch properties
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always

# Logging configuration
logging.level.root=INFO
logging.level.com.hashedin.huSpark=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=ERROR
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.file.name=logs/socio-application.log

# Cache properties
spring.cache.cache-names=users,posts,reports,groups,userStats,postStats,reportStats,groupStats
spring.cache.caffeine.spec=maximumSize=500,expireAfterAccess=600s

# Swagger properties
spring.mvc.pathmatch.matching-strategy=ant_path_matcher